### PR TITLE
refactor value type and to support struct packing/unpacking

### PR DESCRIPTION
**Pull request by guangyuz**
this pr is to implement the feature described in https://github.com/young-rocks/zkmove-vm/issues/13

### CODE REVIEW

**Comment by guangyuz** [comment]
I temporarily removed the type check in binary_op since it depends on the old reference type. I will re-implement it with new reference type. (also need type check for U8, U64, U128, Bool)

**Comment by guangyuz** [comment]
summary of todos: 
- handle the case that the referenced locals is not in the same frame.
- fake value is used to represent the container. It should be replaced by a value that truly represents the container.
- lookup bytecode table is missing in pack/unpack
- we reused args cells in pack/unpack constraints. it can be abstracted as a gadget.

**Review by jules — CHANGES_REQUESTED** [review]
Only a few minor nits, rest LGTM. I'm happy to extract the remaining work to separate issues to break down the work more easily, or you can tackle them in this PR if you prefer. Up to you!

**Comment by guangyuz** [comment]
I would like to merge this pr first since it blocks other tasks.

**Review by jules — APPROVED** [review]
LGTM

**Comment by guangyuz** [comment]
this pr is to implement the feature described in https://github.com/young-rocks/zkmove-vm/issues/13

**Pull request merged**
