### PR TITLE
add constraint for instruction of Call

### PR DESCRIPTION
**Pull request by luxebeng**
add constraint for instruction of Call. which is suitable of struct scenario.

### CODE REVIEW

**Comment by luxebeng** [comment]
It has been verified  based on input parameter of both simple and struct type.
[test_result.log](https://github.com/young-rocks/zkmove-vm/files/10790934/test_result.log)

**Review by guangyuz — COMMENTED** [review]
The solution is complicated, we are still missing constraints on the monotonically increasing of gc. Consider changing the logic of making frame to be, reading all the args out from stack then writing them into locals, instead of reading and writing one by one. It changes the behavior of function call, but simplify the constraints. What do you think? @luxebeng @lerencao

**Comment by nanne007** [comment]
> The solution is complicated, we are still missing constraints on the monotonically increasing of gc. Consider changing the logic of making frame to be, reading all the args out from stack then writing them into locals, instead of reading and writing one by one. It changes the behavior of function call, but simplify the constraints. What do you think? @luxebeng @lerencao

it sounds fine to me. the implementation details of vm can be adjusted to make circuits easier to implement.

**Comment by luxebeng** [comment]
> The solution is complicated, we are still missing constraints on the monotonically increasing of gc. Consider changing the logic of making frame to be, reading all the args out from stack then writing them into locals, instead of reading and writing one by one. It changes the behavior of function call, but simplify the constraints. What do you think? @luxebeng @lerencao

thank you. the implementation is changed into reading all the args out from stack and then writing them into locals now.

**Review by guangyuz — APPROVED** [review]
looks good to me.

**Pull request merged**
