### PR TITLE
code refactor for assign function of memory chip

### PR DESCRIPTION
**Pull request by luxebeng**
1. Move frame_index_table/locals_index_table from MemoryChipConfig into LocalsOpChipConfig.
2. Refactor assign function of memory chip.

### CODE REVIEW

**Review by nanne007 — APPROVED** [review]
LGTM

**Comment by nanne007** [comment]
When I read the part of code, I thought about refactoring the three assignment codes into one function, after all , they shares the same code logic.
Do you think it's possible or not?

**Comment by luxebeng** [comment]
> 

Great point!
Because MemoryChip::assign function is too large, so which is split into 3 functions and moved into corresponding file. Most code is same and should be further refactor into a common function.

**Comment by luxebeng** [comment]
> When I read the part of code, I thought about refactoring the three assignment codes into one function, after all , they shares the same code logic. Do you think it's possible or not?

Just now It has been tried, it's found there is some difficulty: for sake of assign cell is specific for different chip. so which is challenge to abstract into one common  code.

**Pull request merged**
