### PR TITLE
refactor cell, remove dep on meta

### PR DESCRIPTION
**Pull request by nanne007**
trying to resolve #323

### CODE REVIEW

**Comment by nanne007** [comment]
I cannot pass the mock prover verification.
But can generate real proof and verification is ok.
So I think the code should be ok. It's the mock prover that needs to change.

**Comment by nanne007** [comment]
The gates are reduced in an order of magnitude.
Also, proof size is lower too.

```
[functional-tests/tests/testsuite.rs:61:9] cs.degree() = 17
[functional-tests/tests/testsuite.rs:62:9] cs.blinding_factors() = 12
[functional-tests/tests/testsuite.rs:63:9] cs.minimum_rows() = 15
[functional-tests/tests/testsuite.rs:64:9] cs.num_advice_columns() = 156
[functional-tests/tests/testsuite.rs:65:9] cs.num_instance_columns() = 0
[functional-tests/tests/testsuite.rs:66:9] cs.num_fixed_columns() = 35
[functional-tests/tests/testsuite.rs:67:9] cs.num_selectors() = 3
[functional-tests/tests/testsuite.rs:68:9] cs.gates().iter().map(|g| g.polynomials().len()).sum::<usize>() = 1929
[functional-tests/tests/testsuite.rs:73:9] cs.advice_queries().len() = 534
[functional-tests/tests/testsuite.rs:74:9] cs.lookups().len() = 77
[functional-tests/tests/testsuite.rs:75:9] cs.shuffles().len() = 3
[2024-10-17T00:45:20Z DEBUG testsuite] Generate zk proof
[2024-10-17T00:45:28Z INFO  vm_circuit::utils] proof size 43680 bytes
[2024-10-17T00:45:28Z INFO  vm_circuit::utils] prove time: 8294 ms
[2024-10-17T00:45:28Z INFO  vm_circuit::utils] verify time: 20 ms
```

**Comment by nanne007** [comment]
use a feature-flag to control the behaviour of cell

**Review by guangyuz — APPROVED** [review]
LGTM

**Pull request merged**
