### PR TITLE
try to fix adaptive cell's selector

### PR DESCRIPTION
**Pull request by nanne007**

### CODE REVIEW

**Comment by guangyuz** [comment]
1. Enable s_usable on every row will increase the proving time, making step_chip wider can reduce the performance loss here to some extent. We'd better evaluate the performance before merge the pr.

2. should s_step be constrained? For example, the first line must be 1?

**Comment by nanne007** [comment]
> 1. Enable s_usable on every row will increase the proving time, making step_chip wider can reduce the performance loss here to some extent. We'd better evaluate the performance before merge the pr.


while step_chip is wider, but the number of rows is decreased. and although s_usable is enabled for every row, not every row has constraints on that row. only first row of a step has constraints. I doubt they will incur much cost.
I think we can add a benchmark test for the test cases, and trigger it manually in here to do the performance regression test.

> 2. should s_step be constrained? For example, the first line must be 1?

I dont really get the question.

**Comment by guangyuz** [comment]
> although s_usable is enabled for every row, not every row has constraints on that row. only first row of a step has constraints. 

I also believe this doesn't degrade performance too much, just trying to dig a little deeper. My understanding is every s_usable in a step enables a set of constraints. However, since only the first s_step is "1", only the first set of constraints has an effect. But all the other set of constraints still increase the circuit relations. See [Vanishing argument](https://zcash.github.io/halo2/design/proving-system/vanishing.html#vanishing-argument)

> > 2. should s_step be constrained? For example, the first line must be 1?
> 
> I dont really get the question.

Since s_step is a witness, someone may tamper all s_step to zero.

**Comment by nanne007** [comment]
> I also believe this doesn't degrade performance too much, just trying to dig a little deeper. My understanding is every s_usable in a step enables a set of constraints. However, since only the first s_step is "1", only the first set of constraints has an effect. But all the other set of constraints still increase the circuit relations. See [Vanishing argument](https://zcash.github.io/halo2/design/proving-system/vanishing.html#vanishing-argument)

What do you mean by "all the other set of constraints"?
selector is a fix column at last, it'll add a degree to all constraints just like adding a new column.
at a specific step, for each row of this step, only the constraints at first row works although s_usable is always 1, because s_step is 0 besides the first row. and also, constraints for other opcodes are disabled due to the conditions selecting.

and no matter what the value of s_usable is, 
the degree of h(X) in Vanishing argument is still `d(n-1) -n` where `d` is the max degree of all the constraints, and `n` is `pow(2, k)`

> Since s_step is a witness, someone may tamper all s_step to zero.

yes, it needs constraints. I didn't realize that at all.

**Review by guangyuz — APPROVED** [review]
LGTM

**Pull request merged**
